name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR
    uses: sebastienrousseau/pipelines/.github/workflows/labeler.yml@99a39f7d02e76beb2b935fa07b7cd6a46d8bbc65
    with:
      config-path: '.github/labeler.yml'
