name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR
    uses: sebastienrousseau/pipelines/.github/workflows/labeler.yml@3b0c5ce38f72e1b765265a172ac7407daad7f244
    with:
      config-path: '.github/labeler.yml'
