name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR
    uses: sebastienrousseau/pipelines/.github/workflows/labeler.yml@186372a9033a4a2ab2c1157866a5a0bc37410683
    with:
      config-path: '.github/labeler.yml'
