name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

permissions: {}

jobs:
  security:
    name: Security
    permissions:
      contents: read
      security-events: write
    uses: sebastienrousseau/pipelines/.github/workflows/security.yml@186372a9033a4a2ab2c1157866a5a0bc37410683
    with:
      language: 'go'
      severity-threshold: 'moderate'
