name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

permissions: {}

jobs:
  security:
    name: Security
    permissions:
      contents: read
      security-events: write
    uses: sebastienrousseau/pipelines/.github/workflows/security.yml@99a39f7d02e76beb2b935fa07b7cd6a46d8bbc65
    with:
      language: 'go'
      severity-threshold: 'moderate'
